name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  MAJOR_MINOR_BUILD_VERSION: '2.0.0'

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1.4.0
      with:
        dotnet-version: 2.1.202

    - name: Output Run ID
      run: echo ${{ github.run_id }}
    - name: Output Run Number
      run: echo ${{ github.run_number }}
    - name: show full version number
      run: echo ${{ env.MAJOR_MINOR_BUILD_VERSION }}.${{ github.run_number }}

    - name: Update project version
      uses: roryprimrose/set-vs-sdk-project-version@v1.0.3
      with:
        dotnet-version: ${{ env.MAJOR_MINOR_BUILD_VERSION }}.${{ github.run_number }}
        version: ${{ env.MAJOR_MINOR_BUILD_VERSION }}.${{ github.run_number }}
        assemblyVersion: ${{ env.MAJOR_MINOR_BUILD_VERSION }}.${{ github.run_number }}
        fileVersion: ${{ env.MAJOR_MINOR_BUILD_VERSION }}.${{ github.run_number }}
        informationalVersion: ${{ env.MAJOR_MINOR_BUILD_VERSION }}.${{ github.run_number }}

    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Create nupkg
      run: dotnet pack --configuration Release src\ElasticSearch.Extensions.Logging\AM.Extensions.Logging.ElasticSearch.csproj
    - name: Upload nupkg
      uses: actions/upload-artifact@v2-preview
      with:
        name: nupkg
        path: '**/AM.Extensions.Logging.ElasticSearch.*.nupkg'
    - name: Create Release
      id: create_release
      uses: actions/create-release@latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ env.MAJOR_MINOR_BUILD_VERSION }}.${{ github.run_number }}
        release_name: ${{ env.MAJOR_MINOR_BUILD_VERSION }}.${{ github.run_number }}
        draft: true
        prerelease: true
      if: contains(github.ref, "master")
